### ISSUE TITLE
Server not validating minPlayers, maxPlayers, rootLevel

### ISSUE THREAD

**Issue by ctbxx** [LittleBigRefresh/Refresh#134]

**Comment by jvyden** [comment]
Thanks for the bug report. Are you `ctbx` on the official instance? I may have mistakenly restricted you for request forgery - I assumed you wouldn't file any bug reports and that this was just general spam.

**Comment by jvyden** [comment]
Resolved as of [58c39e9](https://github.com/LittleBigRefresh/Refresh/commit/58c39e91a9c5355c1278490508591957cf92753f)
