### ISSUE TITLE
Server not validating 'type' in /scoreboard/user/

### ISSUE THREAD

**Issue by ctbxx** [LittleBigRefresh/Refresh#142]
![0mpeVFgAaW](https://github.com/LittleBigRefresh/Refresh/assets/52249933/84c2ce15-cfc4-46b1-8814-51046188e9e4)

also level [WOMB SURVIVAL](https://refresh.jvyden.xyz/level/157), client sends `<type>7</type>`

[img1](https://i.imgur.com/GKo3R6O.png), [img2](https://i.imgur.com/v5bHIlQ.png)

**Comment by jvyden** [comment]
Not entirely sure how to handle this. Are the only known good values 1-4, and 7? I'm worried about potentially dropping bad scores.
