### ISSUE TITLE
Add configurable profanity filter

### ISSUE THREAD

**Issue by Beyley** [LittleBigRefresh/Refresh#156]
This should have options for common sets of profanity, and a manual blacklist + whitelist

Maybe this could go further than just `/filter` and other upload endpoints, itd be nice if you could as an individual user choose "hmm i want a higher filter/dont want this word at all" and the game wont send specifically to you levels/comments that dont pass said higher filter level (or will censor them), kindof like a word blocklist on social media sites.

**Comment by jvyden** [comment]
This is already the plan with [Bunkum.ProfanityFilter](https://github.com/LittleBigRefresh/Bunkum.ProfanityFilter), which hasn't been worked on a while: https://github.com/LittleBigRefresh/Bunkum.ProfanityFilter/issues/1#issuecomment-1566193822

Although technically untracked in this repository, I'm still gonna close it as this relates to plans in already place.
