### ISSUE TITLE
Recent Activity

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#16]
- List of events in Realm
- Photos uploaded, news, new scores, etc.
- Should be exposed to API

**Comment by Beyley** [comment]
https://github.com/LittleBigRefresh/Refresh/pull/23#discussion_r1141494186
Recent activity should include things like failed logins

**Comment by jvyden** [comment]
This is now being worked on in this branch: https://github.com/LittleBigRefresh/Refresh/tree/recent-activity

**Comment by jvyden** [comment]
Forgot to update status on this - this has been completed in #33.

**Comment by Arcadius2006** [comment]
that was relatively fast
