### ISSUE TITLE
News

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#17]
Format for LBP1 was recently uncovered:

```xml
<news>
    <subcategory>
        <title></title>
        <item>
            <subject></subject>
            <timestamp></timestamp>
            <content></content>
        </item>
        </subcategory>
</news>
```

News in LBP2 is handled in recent activity
https://github.com/LittleBigRefresh/Refresh/issues/16

Thanks to @W0lf4llo for bringing this to my attention.

**Comment by jvyden** [comment]
Whoops, the proper format is something like this:
```xml
<news>
    <subcategory>
        <id></id>
        <title></title>
        <item>
            <id></id>
            <subject></subject>
            <content>
                <!--There can be multiple frame tags-->
                <frame width="">
                    <title></title>
                    <item width="">
                        <slot type="">
                            <id></id>
                        </slot>
                        <npHandle icon=""></npHandle>
                        <content></content>
                        <background></background>
                    </item>
                </frame>
            </content>
            <timestamp></timestamp>
        </item>
    </subcategory>
</news>
```

**Comment by Beyley** [comment]
A partial implementation was added in 657ac736acf1fecd65554436d2a95ac2b2ba8634, but still further work is needed to extend this into a usable state, code should be built off of the existing work, and be sure to only send up to 32 items (at least on PSP, other games may not have this limitation)

**Comment by jvyden** [comment]
No pagination on PSP, I presume?

**Comment by Beyley** [comment]
> No pagination on PSP, I presume?

not that i know of (i wonder if i can hack in extra news slots?)

**Comment by jvyden** [comment]
Bump. Are we in a happy state with this nowadays?

**Comment by Beyley** [comment]
> Bump. Are we in a happy state with this nowadays?

Our news implementation still could use work, we have no way of doing custom news posts, the only news posts that refresh ever puts out is automated posts when a level gets team picked (so that LBP PSP's "Featured Levels" category gets filled out)

**Comment by jvyden** [comment]
I don't think we're going to do this, not for a while at least. Closing as unplanned for now
