### ISSUE TITLE
Send level star ratings to clients

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#180]
currently the game just doesnt display anything, as we send it `0`, this should be `1 - 5`'

- [x] LBP1
- [ ] LBP PSP

**Comment by Beyley** [comment]
To elaborate on this issue, the game seems to not want to display the ratings, even if we send it `averageRating` in the slots response, more work is going to be needed

**Comment by Beyley** [comment]
Sadly the PSP side of this issue is not closed by the linked PR, so it has been unlinked

**Comment by jvyden** [comment]
Noted. Turned this issue into two tasks to reflect that.

**Comment by Beyley** [comment]
PSP ratings are working in prod now, closing.
