### ISSUE TITLE
Move LBP PSP leaderboard endpoints to their own rate limiting bucket

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#183]

**Comment by jvyden** [comment]
@Beyley Are there specific endpoints for PSP or are they the same as the mainline games?

**Comment by Beyley** [comment]
> @Beyley Are there specific endpoints for PSP or are they the same as the mainline games?

Same as LBP1

**Comment by jvyden** [comment]
Not sure how I can do this for PSP in particular then, rate-limiting can't use the database. I can, however, use a different bucket for all the submission endpoints individually, and they won't count towards the global bucket

**Comment by Beyley** [comment]
> Not sure how I can do this for PSP in particular then, rate-limiting can't use the database. I can, however, use a different bucket for all the submission endpoints individually, and they won't count towards the global bucket

The problem is mostly developer/user score get, submission isnt much of an issue

**Comment by jvyden** [comment]
Ah, I see. Okay, I'll just do that across all of them, then.

**Comment by jvyden** [comment]
Lets see, requests will last in the bucket for 10 minutes, and you can have 100 requests sent within that bucket. Exceeding that will cause your requests to get blocked for 5 minutes. Sound reasonable?

**Comment by Beyley** [comment]
> Lets see, requests will last in the bucket for 10 minutes, and you can have 100 requests sent within that bucket. Exceeding that will cause your requests to get blocked for 5 minutes. Sound reasonable?

The PSP makes upward of 50 leaderboard requests every time the community moon is accessed/refreshed, that could be hit very quickly, sadly either the bucket will have to be shorter in time, or the limit will have to be higher

**Comment by jvyden** [comment]
I'll decrease duration to 5 minutes, and bump it up to 250 then. I forgot how inpersistent PSP connections are.

**Comment by Beyley** [comment]
> I'll decrease duration to 5 minutes, and bump it up to 250 then. I forgot how inpersistent PSP connections are.

That should be reasonable, the PSP gracefully handles getting rate limited (displays an error to the user, doesnt crash) so this seems like an acceptable count to me

**Comment by jvyden** [comment]
Cool, I'll push that then.
