### ISSUE TITLE
Add option on site to redirect PSP grief reports as photos to profile

### ISSUE THREAD

**Issue by Beyley** [LittleBigRefresh/Refresh#187]
will require TGA -> PNG/(maybe)TEX conversion

should be toggleable by the user, so they can actually use grief reports as a grief report

**Comment by jvyden** [comment]
All LBP games support decoding PNG files, to TGA -> TEX shouldn't be necessary.

**Comment by jvyden** [comment]
Should we also consider generalizing this for the mainline games? They technically already support taking photos in-game, but you can't really capture the game's UI that way as the option is contained in the popit.

**Comment by Beyley** [comment]
I think that would be a fair thing to generalize, standard in-game grief reports i feel wont see *too* much use anyway, so i dont think people would find it to be a "hassle" to have to toggle the option (on the mainline games it could be made into a chat command too)
