### ISSUE TITLE
Max slot count config setting

### ISSUE THREAD

**Issue by Beyley** [LittleBigRefresh/Refresh#188]
Currently we force the total slot count per game to 100, this should be configurable by an admin both server wide for the default, and per user for exceptions, see [here](https://github.com/LittleBigRefresh/Refresh/blob/48203cb80a47d4b64a93816a575eac5c22af172c/Refresh.GameServer/Endpoints/Game/DataTypes/Response/GameUserResponse.cs#L108) where it would need to be set

**Comment by jvyden** [comment]
Honestly I don't really see why we need a slot limit at all, we can probably just increase it to something huge like 99K

**Comment by Beyley** [comment]
> Honestly I don't really see why we need a slot limit at all, we can probably just increase it to something huge like 99K

Some server owners *might* want to put a cap for filesize/spam reasons? but honestly yeah, theres little reason to want to cap it

**Comment by jvyden** [comment]
Going to proceed with bumping up the limit to `9,999`. :+1:
