### ISSUE TITLE
Implement real-time notifications for LBP clients

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#189]
## Preamble

Apparently, LBP2 and up seem to ignore notifications for non-moderation actions. We can get notifications to show across all games (LBP1/LBP2/LBP3/LBPV, but LBP PSP doesn't have this implemented to my knowledge) by representing the type as `moderationNotification`:

```xml
<notification type="moderationNotification">
    <text>Sample Text</text>
</notification>
```

## Implementation

We should test if the game can receive multiple notifications at a time. If not, we can just grab the user's notifications with a count of `1`. I think up to 3 at a time is acceptable, though.

Anyways, once we have the notification(s) we should format it something like this:
```
Notification Title: Notification Description
```
Or we can skip the title entirely:
```
Notification Description
```

Its probably also worth mentioning the instance name in the notification so the user can differentiate between LBP notifications and server notifications, since the game itself doesn't really appear to distinguish anything.

## Credits

Shoutouts to @Zaprit for discovering this.

https://discord.com/channels/1049223665243389953/1055225660085383258/1158218671378935920

**Comment by jvyden** [comment]
Also we should make a debug command for adding notifications

**Comment by Beyley** [comment]
> ## Preamble
> 
> Apparently, LBP2 and up seem to ignore notifications for non-moderation actions. We can get notifications to show across all games (LBP1/LBP2/LBP3/LBPV, but LBP PSP doesn't have this implemented to my knowledge) by representing the type as `moderationNotification`:
> 
> ```
> <notification type="moderationNotification">
>     <text>Sample Text</text>
> </notification>
> ```
> 
> ## Implementation
> 
> We should test if the game can receive multiple notifications at a time. If not, we can just grab the user's notifications with a count of `1`. I think up to 3 at a time is acceptable, though.
> 
> Anyways, once we have the notification(s) we should format it something like this:
> 
> ```
> Notification Title: Notification Description
> ```
> 
> Or we can skip the title entirely:
> 
> ```
> Notification Description
> ```
> 
> Its probably also worth mentioning the instance name in the notification so the user can differentiate between LBP notifications and server notifications, since the game itself doesn't really appear to distinguish anything.
> ## Credits
> 
> Shoutouts to @Zaprit for discovering this.
> 
> [discord.com/channels/1049223665243389953/1055225660085383258/1158218671378935920](https://discord.com/channels/1049223665243389953/1055225660085383258/1158218671378935920)

PSP has the code in place to call the endpoint/parse the response, but its never called, so it can be assumed non-applicable, perhaps notifications can be put into `news` or `announce` for PSP? announce is displayed and news is updated every time you log in (which is often on PSP, since you get auto-logged out when you play/edit any level)

**Comment by jvyden** [comment]
Hmm, news is probably a better place for global announcements, e.g. the one on production about Outlook.

Notifications are already a part of `announce` so I'll leave them there.

**Comment by jvyden** [comment]
Sure enough, I'm able to chain multiple notifications:

![image](https://github.com/LittleBigRefresh/Refresh/assets/40577357/5dc908c9-d74f-48e1-9385-060072b56632)

```csharp
    [GameEndpoint("notification")]
    [MinimumRole(GameUserRole.Restricted)]
    public string Notification(RequestContext context, GameUser user, GameDatabaseContext database)
    {
        return """
               <notification type="moderationNotification"><text>Sample Text 1</text></notification><notification type="moderationNotification"><text>Sample Text 2</text></notification>
               """;
    }
```

**Comment by jvyden** [comment]
Sweet, got it working.

![image](https://github.com/LittleBigRefresh/Refresh/assets/40577357/ae2d5206-9eb5-428c-a35e-32dd9886b192)

**Comment by jvyden** [comment]
Added in [ae8094e](https://github.com/LittleBigRefresh/Refresh/commit/ae8094ea28d114c00155479ee1a111359e9d56db)
