### ISSUE TITLE
Add support for importing GTF textures

### ISSUE THREAD

**Issue by Beyley** [LittleBigRefresh/Refresh#194]
According to [this conversation](https://discord.com/channels/1049223665243389953/1049225857350254632/1159940160885104812), modded textures can use the GTF format, and while these are marked as Potentially Unwanted assets, it would still be good to support proper importing/PNG conversion of these assets for any 3rd party instances that want to allow modded textures

This should be done as an implementation of an ImageSharp `ImageDecoder`, and we may want to upstream it into `ImageSharp.Textures` if applicable

The header structure of the file is provided here:
```cs
struct CellGcmTexture 
{
        public byte format;
        public byte mipmap;
        public byte dimension;
        public byte cubemap;
        public uint remap;
        public ushort width;
        public ushort height;
        public ushort depth;
        public byte location;
        private byte _padding;
        public uint pitch;
        public uint offset;
}; 
```

Attached is a compressed archive containing a GTF file, and the corresponding equal DDS file
[test_256_dxt1.tar.gz](https://github.com/LittleBigRefresh/Refresh/files/12835347/test_256_dxt1.tar.gz)

The main usecase for this would be a site page for moderating modded assets

**Comment by TorutheRedFox** [comment]
note: the CellGcmTexture struct doesn't include the file magic

**Comment by Beyley** [comment]
More relevant resources: 
https://github.com/RPCS3/rpcs3/blob/23cb67e0a10f7d7ecf39122fa697af8dcc30690e/rpcs3/Emu/RSX/GL/GLTexture.cpp#L77C10-L77C10
https://github.com/RPCS3/rpcs3/blob/23cb67e0a10f7d7ecf39122fa697af8dcc30690e/rpcs3/Emu/RSX/GL/GLTexture.cpp#L112
