### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#20]
Similar to Discord. Will be pretty helpful for larger instances

- User can have multiple roles (?)
- Roles detail what actions can be taken by the user (can this user post comments, can this user ban other users, etc.)
- Roles may optionally display a badge on the users profile
- Has default roles (User, Admin) but still configurable by administrator

To implement:
- [x] Administrator role
- [x] User role (default)
- [x] Restricted role
- [x] Banned role

**Comment by Arcadius2006** [comment]
could it be possible to create a "user" that represents a group and then let people upload levels to that somehow?

**Comment by jvyden** [comment]
Probably, the goal is to strip `GameLevel`s of needing a `Publisher` at all (for things like story levels) so I don't see why we couldn't fake a user

**Comment by Arcadius2006** [comment]
its more about the uploading part, how would you do that

**Comment by jvyden** [comment]
Probably upload the level to your own profile and then transfer it

**Comment by jvyden** [comment]
The system for this has been implemented, now we just need things to do with it
