### ISSUE TITLE
Add a chat command that lets you enter any level

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#200]
Add a command usable in the ingame chat that can forcibly load a level, regardless of the fact that it's locked or a sub-level

This option would be only available to administrators by default, and level would be accesed by typing in the command proceeded by the level's hash. This could also be modified to accept guids instead, allowing for exploration of levels stored in gamedata

**Comment by jvyden** [comment]
This is especially important now that we have the February 2023 archive. Don't know about guids, but certainly for normal SHA-1 hashes.

**Comment by jvyden** [comment]
Done
