### ISSUE TITLE
Notifications for score overtakes

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#232]

**Comment by turecross321** [comment]
Should this only be sent if the person who was overtaken was previously top 5 or something like that?

**Comment by jvyden** [comment]
Top 3, or maybe just top 1, but yeah.

**Comment by turecross321** [comment]
How do you think links should be formatted in notifications?

Should it be like markdown maybe?

`$"Your #1 score on [{level.Title}]({level.LevelId}) has been overtaken by [{user.Username}]({user.UserId})"`
