### ISSUE TITLE
Ability to mark a level as a reupload

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#233]

**Comment by speedyman09** [comment]
Probably a good first issue

**Comment by Beyley** [comment]
Given we already have a special user for deleted users, imo we should yes, the user should be removed, and it should instead be marked as uploaded by `!UnknownAuthor`, or maybe `!$OriginalAuthor$`, ofc with `$OriginalAuthor$` replaced with the original author. Then we'd need a way of marking who the original author is (and in the future, let that be moved to be owned by the original author, if they register an account and we verify they are who they are)
