### ISSUE TITLE
Ingame Level Filtering

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#249]
LittleBigPlanet 2, Vita and 3 all let you filter through your search by number of players, tag, game, and text

these do not work
![image](https://github.com/LittleBigRefresh/Refresh/assets/93880348/4113b50a-95ac-43da-ae0c-1657af6ce53f)
please fix!

**Comment by jvyden** [comment]
Why isn't this closed again? Just tags & labels I presume?

**Comment by Beyley** [comment]
> Why isn't this closed again? Just tags & labels I presume?

yup

**Comment by jvyden** [comment]
Closing in favor of #260.
