### ISSUE TITLE
Story levels category doesn't include Game API endpoints?

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#253]
Will need investigation into effects of this. I know LBP makes requests to `/lbp/slots/developer`, so I have to feel like something is broken as of right now.

**Comment by jvyden** [comment]
Probably okay. We've had no reports of issues with this.

**Comment by Toastbrot236** [comment]
Apparently this endpoint is only called so that lbp can show the current player counts for all story levels at once.
