### ISSUE TITLE
Crop level/user icon on website and webhook to 1:1

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#270]
Since the final product will always be square, it is useless to keep the full image data.

crop them automatically where applicable

**Comment by jvyden** [comment]
Should be fairly simple, given that we already depend on ImageSharp.

The full asset should *always* be retained, so this would be a new API endpoint. I don't know how it would look past that though. Needs more planning

**Comment by jvyden** [comment]
@Beyley How do you feel about this taking this? You've worked on image importing a lot recently so it would probably be way better if you handled it.

**Comment by Beyley** [comment]
I'd be fine handling this. One thing to question is, should this also be done to photos when set as a user avatar ingame? LBP1 will visually squish a photo if its not a 1:1 aspect ratio

**Comment by jvyden** [comment]
Probably. That's probably an extra step we can do when we handle #309, but I'd say that's out of scope for just this.

**Comment by Beyley** [comment]
> Probably. That's probably an extra step we can do when we handle #309, but I'd say that's out of scope for just this.

How i'm envisioning fixing this issue will also involve fixing #309, since mentally im grouping these together into "being able to process images, and replace hashes live"

**Comment by jvyden** [comment]
Then yeah, I'd say hold off on that bit. This should just be a API feature for now just to land us somewhere.

**Comment by jvyden** [comment]
In terms of the API I'm thinking of a simple extension to the `/api/v3/assets/{hash}/image` endpoint. We can either have a parameter like so: `{hash}/image?square=true` or have another endpoint (probably easier code-side) like this: `/api/v3/assets/{hash}/square`

Up to you, I don't mind which.

**Comment by Beyley** [comment]
How im thinking of solving this is having extra methods on `GameAsset` that will return a hash for a converted asset, eg. 

`GameAsset.GetAsAvatar(TokenGame game) -> string (hash)`

If you pass in Website or LBP1, ittl always give you a cropped to 1:1 aspect ratio PNG file
If you pass in LBP2 or LBP3, if the source is a TEX or PNG file, ittl do nothing and just return the same hash, or if the source image is not a TEX or PNG, convert to PNG, and return the hash for that (LBP2 and LBP3 will crop for us)

If its LBP Vita, if its not in a format Vita can read, ittl convert to PNG (without cropping) and send it to the Vita (assuming Vita auto-crops like LBP2 does)

there will also be other methods for other types

like `GameAsset.GetAsPhoto`, which will _only_ convert into a supported texture format for the passed `TokenGame`, and do no extra cropping

(obv also with caching)

This would mean the API doesnt have to be extended at all, and its all done transparently by the server

**Comment by jvyden** [comment]
Hmm, yeah I see your point now. Definitely best to kill two birds with one stone for this one.

This one is difficult to think about so I'll back off for now haha
