### ISSUE TITLE
Dive In does not work

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#271]
whenever you try to dive in, it just tells you nobody is playing regardless if anyone is actually playing

**Comment by Beyley** [comment]
Are you sure that you have your settings correct? I am unable to replicate this. I just tested and was able to dive into someone else on RPCS3

**Comment by jvyden** [comment]
Dive-in also filters out players that have joining disabled. It would be helpful if you could paste the contents of https://lbp.littlebigrefresh.com/api/v3/rooms when you're experiencing this issue so we could help debug further.

**Comment by jvyden** [comment]
Closing as stale
