### ISSUE TITLE
RFC: Relocker, eg. Ensuring our long time viability of Refresh on real hardware

### ISSUE THREAD

**Issue by Beyley** [LittleBigRefresh/Refresh#278]
# Overview
PSN for the PSP is not long for this world, it _will_ fully be shut down at some point (and already partially has, PSN friends on PSP is completely broken). We need to provide a replacement to make sure that real hardware doesnt get stalled for maybe months as a full PSN replacement is created by others, and I feel we need to get ahead of the curve, rather than panic once it does get shut down. PS3 will also be on the chopping block some day, whether it be 5 years or 15 years away, when that happens, we will lose a lot of our players for an extended period of time, and I feel that may kill the growth of the project in its tracks.

I propose we give the system of plugins/tools the "brand name" of Relocker, with related menus/tooling being named accordingly as well. The name comes from the visual metaphor often used to describe encryption/signatures, which is a lock and key, combined with the fact we will need to implement np ticket signing.

This proposal will focus on the PSP side of things, since that is likely to be shut down long before PS3.

I propose we write a CFW plugin to re-implement the PSN syscalls that the system uses to communicate with PSN, this will include the full suite of `sceNp*` and related syscalls, all will be reimplemented using a light kernel plugin, communicating over a custom HTTP(S) protocol.

The groundwork for this is already in Allefresher for PSP, it just needs to be finished and combined with a server implementation

It is important to note that this is _not_ a reimplemenation of the PSN protocol. It will provide the same `sceNp` syscall interface, but the underlying implementation will use a completely distinct protocol.

The end goal for this proposal is that the console will not need to be logged into (or even have access to) Sony's PSN servers to be able to play on Refresh and other PSN-enabled custom gameservers, instead users would be able to login on-console with a separate user+pass separate from PSN, and the console would never even need to contact PSN to allow online play.

This will be a separate project from Refresh, with an API to allow integrations between Refresh (and any 3rd party) and the Relocker server

# Implementation
Relocker will have 2 APIs exposed, an *extremely* basic API for the CFW plugins to contact, and an external API for others to use. 
The CFW API is intentionally left as basic as possible, to allow the plugin code to be extremely small, and to not need to pack in something an XML or JSON deserializer. This could all be implemented in a CFW plugin very basic logic, calling the builtin `sceHttp` API.

datatype key:
`UINT = 32-bit unsigned integer`
`STRING = length prefixed UTF-8 string` (length is a `UINT`, and counts the amount of bytes in the string, not codepoints)
`BOOL = 32-bit unsigned integer, with 0 meaning FALSE, and non-zero meaning TRUE`
`BYTE = a single 8-bit byte`
`{...} means an arbitrarily long list of the object contained within`

# Plugin API

## `POST /np/v1/login`
This endpoint takes in a *very* simple request body, defined as `[STRING email][STRING sha256_hashed_password]`
It will return the following possibilities
 - 200 OK, with the response body defined as `[UINT np_ticket_byte_length]{BYTE np_ticket_byte}`
 - 404 Not Found, indicating a user was not found by that name
 - 401 Unauthorized, indicating an incorrect password

## `GET /np/v1/friends/{username}`
This endpoint returns the following possibilities
 - 200 OK, with a response defined as such, `[UINT userCount]{[STRING username]}`, with the username list being the usernames of the users that are friends
 - 404 Not Found, indicating a user was not found by that name

CFW plugin implementations *must* ignore extra data after the read data, to allow future expansion of the data returned without a breaking change.

These 2 endpoints are enough to implement all of the functionality required to log-in to a custom server from real hardware, and get most in-game features working. An API version is embedded into the URL to allow us to make breaking changes to the API in the future, if required.

Other APIs will be implemented as needed, but the first goal will be logging in, np ticket generation, and friends, with more advanced PSN features being implemented after the basics have been tested well.

# External API

## `GET /np/api/v1/friends/{username}`
This endpoint returns a JSON datastructure following the standard Refresh API response, an example response layed out as follows 

You will automatically become friends with someone by mutually hearting eachother in LBP.
```
{
	"success": true,
	"data": {
		"friends": [ 
			{ 
				"username": "friend1", 
				"addedAt": "DATE_HERE" 
			},
			{ 
				"username": "friend2", 
				"addedAt": "DATE_HERE" 
			} 
		]
	}
}
```

# Other loose ends

Our [np ticket library](https://github.com/LittleBigRefresh/NPTicket) will have to be expanded to be able to sign and create our own np tickets using a custom private key.

Refresh should add a configuration option to allow server owners to add custom np ticket public keys.

**Comment by jvyden** [comment]
Yeah, this should definitely be a different project entirely. The API and communication style looks good given the circumstances, but I strongly disagree with tightly coupling it with LBP or any game in particular.

The scope of this is too thin to be practical. Frankly, I don't see the point at stopping at the game-level. People are going to want a full PSN implementation, hell, some already do. Think about people with console bans on PS3, for example. It's not just about reviving LBP, I think if we're going to think about this, we should think about reviving PSN on PSP entirely.

Yes, it will be difficult, but at the end of the day I think it's worth the effort. I'm sick of stressing over firmware updates, spoofing, getting banned, the whole bit, as I'm sure many others are. I think it's a good opportunity to relieve some of those stresses from homebrew users and potentially bring in some cool integrations.

**Comment by Beyley** [comment]
For the PSP at least, PSN integeration is *extremely* basic, so i dont think it would be too much effort to increase the scope to the entirety of the `sceNp*` suite of syscalls. I'm trying to avoid re-implementing the PSN protocol itself for practicality concerns (plus i feel like a PSN protocol RE project would pique sony's interest more, which we want to avoid), but if the PSN related options on the PSP XMB all use standard syscalls, then it should be possible to do a *full* PSN replacement using a only CFW plugin that just hooks all the syscalls, i'll update the proposal to account for this.

**Comment by jvyden** [comment]
> plus i feel like a PSN protocol RE project would pique sony's interest more, which we want to avoid)

Which law does this break? I don't see how modifying your console to save it from being e-waste in the future would draw Sony's attention

> but if the PSN related options on the PSP XMB all use standard syscalls

It's possible it might make requests manually but I doubt it, there seems to be a syscall for practically everything PSN-related at least on PS3

**Comment by Beyley** [comment]
> Which law does this break? I don't see how modifying your console to save it from being e-waste in the future would draw Sony's attention

Doesnt break any laws, but big companies are big companies and if they decide we arent working on a project anymore, we arent gonna work on it anymore, i dont exactly have the funds to fight that. So i'd rather take what feels like the safer approach and just reimplement the syscalls with a different protocol through a CFW plugin. Theres also difficulty, tmk everything in the official PSN protocol is HTTPS with a verified certificate, and ive _attempted_ to get parts to talk over HTTP before (mainly the `imgw` friends endpoint), and it was a non-trivial effort.

**Comment by Beyley** [comment]
Proposal has been updated with more info, issue should be moved to separate repo once it exists

**Comment by uhwot** [comment]
I think it's better to reuse the RPCN protocol rather than create a custom one, most of the online features are already implemented there anyways and we could reuse the existing RPCN server code.
It could also allow crossplay between real PS3s and RPCS3, assuming emulation differences aren't an issue on a specific game.

**Comment by jvyden** [comment]
I wouldn't mind support for RPCN *clients*, but RPCN as a server as-is isn't desirable for a couple reasons.

RPCN's server as officially implemented by the RPCS3 team uses SQLite as a database backend. This isn't problematic on it's own, but causes issues when expanding scope (which a full PSN implementation will inevitably need). The official RPCN server has had it's registration list wiped a couple times now for a reason I haven't investigated but I'm fairly certain it's because the migrations you can do in SQLite are quite limited when it comes to altering tables.

Another thing is it's written in Rust. I imagine we'd be making lots of changes and Rust isn't something Beyley or I are really familiar with.

RPCN is also a custom UDP-based protocol that uses it's own binary format instead of plaintext. This makes it a bit difficult to support external API integrations since you'd need to write something that speaks that protocol for every language whereas HTTP is universally understood.

**Comment by Beyley** [comment]
I agree with jvy here, i would highly prefer to roll our own server and protocol. Having an RPCN frontend for RPCN clients is something that can be (and should be) looked into at a later date to allow cross play, but id prefer our own real hardware plugins to use a simple HTTP protocol. It simplifies implementation and will let us use less code and memory overall, we have to fit all this into a kernel plugin, which on a PSP 1000 thats going to be tough if we have a full custom UDP networking solution with retries and so on. One of the main goals of the protocol is to keep as much code as possible on the server and use as much existing networking infrastructure provided by the OS as possible.

**Comment by jvyden** [comment]
I'm closing this as I don't see us doing this anytime soon.

If this becomes urgent or we have the resources/willpower/know-how to pull this off then we can talk about this.
