### ISSUE TITLE
Automatic Account Creation

### ISSUE THREAD

**Issue by turecross321** [LittleBigRefresh/Refresh#281]
From discord:

If a user tries logging in through the game without having created an account, the server should create one automatically, and give the user a registration-finish-code through the announcements screen. This code is then used to assign an email & password to the user's account through the website (the announcement should also obviously link to the registration page). This would mean that registration is more straightforward; simply patch your game, open it up and follow the on-screen instructions.

If the user ignores the announcement and presses x, the server could just log them in and let them play, or maybe put them in a read-only mode, or just straight up refuse their connection (maybe use the EULA instead of the announcements page to show the registration code if that's the chosen option).

This would be a good middle ground between the security of refresh where everyone needs an assigned e-mail and password, and the convenience of Project Lighthouse - but this would actually work throughout all the games unlike Project Lighthouse's `/setemail` command that only works on some of the LBP games. Additionally, this would render the common mistake where someone registers an account with a non-matching username impossible.

This seems like a nitpick, but there have been multiple people who do not realize that they have to register an account on the website before being able to actually log in, and since the game shows an identical error as to if the server was down, many users are left confused.

**Comment by jvyden** [comment]
I think the best mode for unregistered users is to be able to let them play, but yeah, they should be stuck in a read-only state until they sign up. We could give them a token for a shared `!Guest` account with the `Restricted` role to achieve this state easily. Lighthouse automatically creates accounts, which means it's prone to people accidentally creating them after migrating from other instances. No data should persist for temporary sessions.

Is this intended to completely replace website registration or to simply add another method of account creation from the game side?

**Comment by turecross321** [comment]
I was thinking that it should replace the current registration system.

**Comment by turecross321** [comment]
That's reasonable. We could at that point not actually implement automatic account creation at all, but rather just a read only mode, and have the announcement page say that you have to register an account on the website.

**Comment by jvyden** [comment]
If you had the registration code system then you'd solve mismatched usernames by having that code correspond to your username and platform. You would just have to punch in your email and password to activate your account fully.

The current registration system should be secondary to this to help UX (maybe it could be a "Don't have a code?" button?)

If you'd like to rewrite your proposal then I'd be happy to implement something like this. :+1:

**Comment by turecross321** [comment]
Alright, sounds good 👍
