### ISSUE TITLE
Issues with viewing categories on LittleBigPlanet 3

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#302]
Viewing categories in LBP3 works fine until you hover over them, then they'll suddenly say that no search results have been found for that category

going into the list view doesn't help anything, and the game still claims it couldn't find anything despite being able to preview the first level in the list (along with it's title and description) literal seconds ago

**Comment by Arcadius2006** [comment]
note: the pop-ups when you hover over one of the two categories in the community tab DOES work and will take you to the level prompted up

**Comment by jvyden** [comment]
Can't repro, assuming this was fixed at some point.
