### ISSUE TITLE
Moving/Republishing a level completely overwrites it's atributes

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#310]
When you move one of your levels to another spot on your earth, every atribute that isn't the level itself gets changed. Teampicks disappear, Game version changes, ect.

**Comment by jvyden** [comment]
Easy fix with a simple check along the lines of something like this:
```
if(republishing && old.LevelHash != new.LevelHash) {
   new.TeamPicked = old.TeamPicked;
   new.Version = old.Verison;
}
```

I think it's fair to keep old behavior if the actual level contents change.
