### ISSUE TITLE
"News to read" pop-up pops up regardless of if any actual news was posted recently

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#343]
the "Read News" pop-up should only appear when there are unread server announcements in your feed. This pop-up instead ALWAYS pops up, and seeing it pop-up is very annoying

please do something about this.

**Comment by jvyden** [comment]
This will be fixed with the implementation of filters. LBP just determines whether to show the popup by making a news-only request in Recent Activity and checking if it got any recent results.

Closing as duplicate of #248.
