### ISSUE TITLE
Support for PS4 Little Big Planet 3 (jailbroken PS4)

### ISSUE THREAD

**Issue by TroubledPerson** [LittleBigRefresh/Refresh#352]
Jailbroken ps4's can have patches in some ways, possibly allowing connection to this server. Wondering if this could incorporate into this server software. Low priority but a consideration for preservation efforts in future. However either  some features would be impossible to work such  as trailers as it is a ps4 exclusive unless a workaround is present

**Comment by Beyley** [comment]
Not planned unless the official servers shut down for good. We dont want to compete.

**Comment by imadeagithubaccountforthis** [comment]
should we reopen this?

**Comment by Beyley** [comment]
> should we reopen this?

See #410
