### ISSUE TITLE
Rating Reviews

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#449]
LittleBigPlanet allows you to rate comments and reviews, which refresh is currently missing. implementing this would be benefitial, since rating reviews places them higher or lower depending on the yay/boo ratio it gets

**Comment by jvyden** [comment]
Comments are already implemented. @Beyley do we have ratings for reviews?

**Comment by Arcadius2006** [comment]
i tried yaying a review last time and it didnt work

i then incorrectly assumed the review yays and comment yays were tied to eachother

**Comment by Arcadius2006** [comment]
https://github.com/LittleBigRefresh/Refresh/issues/82#issuecomment-1913345232 i noticed this comment i made, i'll post it here so nobody forgets about it
