### ISSUE TITLE
uploading levels on RPCS3 is bugged (LBP2) (prepare for a short essay)

### ISSUE THREAD

**Issue by Toastbrot236** [LittleBigRefresh/Refresh#504]
There is this issue thats existed for longer where if you edit a level for some time on RPCS3 and try uploading it, it will always fail. Its happening on LBP2 but idk if this also happens on LBP1 and 3.
When i set up my own private instance and tried uploading one of those "problematic" levels, the level would fail to upload and the server would log a warning three times that the hash of an asset is not the same as the one Refresh calculates from the asset and therefore say the asset might be corrupt (even tho its working fine on rpcs3). Itd log that same warning 3 times and then stop the upload. 
My first idea was to have the ReadAndVerify method (i believe it was called that) in the AssetImporter to not return null if the assetHash was unequal to hash, making the hash of the asset stay the way it was. The level would successfully upload but when i tested the level (by loading a profile that didnt have these assets on it and then restarting the game) lbp would successfully get one resource and then stop loading the level, saying the level had failed to load.
My second idea was to overwrite the hash with assetHash if it mismatched. This would give the same result as the first idea. For this i was actually able to come up with a possible explanation, that being the assets were still being referred by their old hash in the root level. But i had no idea why exactly the first idea, not overwriting the hash at all, was failing.
So now my third idea is to just upload 2 assets if the hash mismatches, one with the og hash and one with the corrected assetHash. Ive written some bad and untested code for this yesterday which i still have to test. Incase this actually ends up being a working workaround, i think i (or we if anyone is interested in finding a workaround for this rpcs3 bug) should make it so the copy of the asset not only gets created if the hash mismatches, but also only if the user is on rpcs3. Maybe also limit creating a copy to a command the user has to run to make sure the user is sure that the asset theyre trying to upload isnt actually corrupt. Id have to learn how commands actually work and how to make the method that calls the ReadAndVerify method know whether the user who is trying to upload the asset is on rpcs3 or not.
What do you think? Is this a bad idea?
Ill most likely edit this issue and add more info when im actually on my pc.

**Comment by jvyden** [comment]
> the server would log a warning three times that the hash of an asset is not the same as the one Refresh calculates from the asset

Then the asset is corrupt, or a reverse proxy is corrupting it. This isn't a problem with Refresh.

> lbp would successfully get one resource and then stop loading the level, saying the level had failed to load.

Because the resource it downloaded is corrupt and doesn't match the hash.

You can check this yourself by running `$ sha1sum <file>` to get the SHA-1 hash of the file in the data store and observe that the two columns do not match.

**Comment by Toastbrot236** [comment]
shit where is the delete button
