### ISSUE TITLE
Users hearted on LBP2/3 don't show as hearted on LBP1

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#525]
I'd also like to add that trying to heart them again does nothing (presumably since according to the server the user is already hearted)

**Comment by Arcadius2006** [comment]
oh, and apparently it's inconsistent too: i viewed the Hearted Creators page and the creator i was looking at suddenly WAS hearted

that's very odd

**Comment by jvyden** [comment]
This is probably the game not fetching the hearted creator list before viewing the profile in question. Nothing we can really do in this case.
