### ISSUE TITLE
Can't view someone's review history

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#542]
A user's profile usually has a list of reviews they made that you can scroll through

but, the tab itself seems to be missing, which i'm assuming is because the feature is currently unimplemented

**Comment by jvyden** [comment]
[we should have the endpoint for this](https://github.com/LittleBigRefresh/Refresh/blob/main/Refresh.GameServer/Endpoints/Game/ReviewEndpoints.cs#L82) but maybe we're missing something on the user object. i'd call this a bug in that case

**Comment by Arcadius2006** [comment]
i'd like to add that it DOES show up on LBP3, so this issue is LBP2 (and maybe vita?) exclusive
