### ISSUE TITLE
Busiest level category always empty

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#553]
even when there are users playing community levels online, they don't seem to show up in the Busiest category on LBP2

**Comment by jvyden** [comment]
It's probably worth cleaning up the logic for Busiest anyways.I'll take a look next time I work on Refresh.On Jul 6, 2024, at 5:23 PM, Arcadius2006 ***@***.***> wrote:﻿
even when there are users playing community levels online, they don't seem to show up in the Busiest category on LBP2

**Comment by jvyden** [comment]
From what I can tell (from the website) it seems to work fine. It should also work fine game-side since it uses the same code, using the same version-filtering code as the rest of the categories.

It might just be that not many people are playing on LBP2 at that moment.
