### ISSUE TITLE
Recent Activity does not work on LBP3

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#581]
Instead of showing the Recent Activity list correctly, the game will attempt to load it for a bit before it decides it cannot find anything.

this may have something to do with the fact that it is way more customizable than LBP2's recent activity tab is

attached below are pictures of what exactly you can customize in LBP3's Recent Activity:
![image](https://github.com/user-attachments/assets/3b63d83a-24fe-4df8-a0cd-b7e51f0f351f)
![image](https://github.com/user-attachments/assets/0d8f92fb-b729-482e-a6ab-c64cfe5ba700)
![image](https://github.com/user-attachments/assets/eb726b26-3d07-4f95-afe4-b01a6aa15ce3)

**Comment by Beyley** [comment]
This has already been resolved in #578

**Comment by Arcadius2006** [comment]
i literally checked it RIght Now, though

it did not work

**Comment by Beyley** [comment]
> i literally checked it RIght Now, though
> 
> it did not work

It is an open PR, just wait for the next release

**Comment by Arcadius2006** [comment]
ooooh, okay, i see

sorry for the inconvinience
