### ISSUE TITLE
Implement User Groups

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#583]
Basically, a group would be a fake profile where multiple people attached to it can publish levels freely under the profile's label.

just like a fake user, the group would be marked with a special character (like > for example? or something similar)

one thing i'm not sure of is how you would decorate such an earth without external modding tools, but maybe you could also copy the earth off any player in the group?

of course, this doesn't have to be implemented, but it'd be cool for big projects which require multiple people

**Comment by speedyman08** [comment]
https://github.com/LittleBigRefresh/Refresh/issues/77

I believe this issue exists already

**Comment by Arcadius2006** [comment]
whoops, it does

**Comment by Arcadius2006** [comment]
guess ill close it then
