### ISSUE TITLE
LBP hangs when attempting to find levels via a tag

### ISSUE THREAD

**Issue by speedyman08** [LittleBigRefresh/Refresh#612]
![image](https://github.com/user-attachments/assets/056dbda1-8b57-465f-ab19-f45f23a60c5d)
infinite load

**Comment by Beyley** [comment]
unable to replicate, are you sure you patched your digest key?
![image](https://github.com/user-attachments/assets/dff007ab-1bb4-4209-874d-c4de7b177f9a)

**Comment by speedyman08** [comment]
![image](https://github.com/user-attachments/assets/64a39d7a-c430-4259-98bd-68e6caa7a380)
works completely fine now, must have been an rpcs3 issue/something on my end
