### ISSUE TITLE
Dive In not working at all in LBP2

### ISSUE THREAD

**Issue by RedRavenYouTube** [LittleBigRefresh/Refresh#641]
The Dive in feature in LBP 2 will not work and every time I try to connect to a player it says it failed and I would be sent back to my pod but the biggest issue is that the dive in screen does not go away so I have to go into the menu again then close it to get back. And yes, I have an activated account. My user is RedRaven_LOL. I really hope it is a server issue and not an account issue.
![bug](https://github.com/user-attachments/assets/631a452d-ec1a-417a-adae-b6ad4924250b)

**Comment by Arcadius2006** [comment]
sign out and into PSN again - this is an issue with the game's P2P networking, not LittleBigRefresh

**Comment by RedRavenYouTube** [comment]
do I need to reset the game?

**Comment by Arcadius2006** [comment]
no, you actually want to keep it open

press the PS Button, navigate to Account Managment, press Triangle, and choose the sign out option

from there, you can sign back in and try again

**Comment by RedRavenYouTube** [comment]
what happens when I enter the game after signing out?
Trying to be precautious

**Comment by Arcadius2006** [comment]
you are not supposed to leave the game

signing out outside of the game won't do anything and will only waste your time

**Comment by RedRavenYouTube** [comment]
I mean if I press the ps button, log out, and go back without signing in what will happen? I am talking about the menu that happens mid game when the ps button is pressed

**Comment by Arcadius2006** [comment]
also nothing: the game will prompt you to sign back into PSN again. it makes no difference whenever you do it in or outside of XMB

**Comment by RedRavenYouTube** [comment]
so I just need to log out and back in in the game xmb

**Comment by Arcadius2006** [comment]
yes, i have said this already.

**Comment by RedRavenYouTube** [comment]
ok lemme try

**Comment by Arcadius2006** [comment]
you should probably also close the issue, since it is again unrelated to Refresh in the first place

**Comment by RedRavenYouTube** [comment]
ok
