### ISSUE TITLE
PROBLEMA EN EL AUTO DISCOVER

### ISSUE THREAD

**Issue by LBP3-LOVER** [LittleBigRefresh/Refresh#685]
hola, tengo todo correctamente pero por alguna razon me dice "locked for littlebigrefresh (refresh)" no se porque ocurre esto pero enserio necesito una explicacion, investigue acerca del tema y creé la carpeta Actualizar en el lugar correcto con el codigo correcto y el nombre correcto y nada, tambien intente en otros dispositivos y lo mismo, repito tengo webman mod y todos sus archivos y hen con todos sus achivos, tambien le hice jailbreak y todo, esto me ocurre al momento de usar auto discover en el patcher "refresher"

**Comment by jvyden** [comment]
Duplicate of #686
