### ISSUE TITLE
Login/Registration security

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#78]
- [x] Enforce tighter rate limits on these endpoints
- [x] Don't allow user to be registered immediately, wait for game handshake to activate account
~~- [ ] Trial period for new users? Don't allow commenting/relations through API for a little while, but may be too strong of a measure~~ Unnecessary for now, we'll gague later
- [x] Simple password requirements (8 characters, don't want to be too strict on this)
- [x] Email verification. Must-have.
- [x] Users should not be able to steal accounts from other platforms. A PSN account should not be able to be logged into from RPCS3 if not explicitly allowed by that user.

**Comment by speedyman09** [comment]
Shouldn’t most of these only be applicable to refresh-web?

**Comment by jvyden** [comment]
Refresh-web is just a JavaScript front-end, so no. Most of these things will have to be done in Refresh.

Despite what Google seems to think with their Web Environment API, **you should never trust the client for any reason**.

However, since passwords are sent via SHA-512 hashes, password requirements will have to be done on that side.
