### ISSUE TITLE
Level reviews

### ISSUE THREAD

**Issue by jvyden** [LittleBigRefresh/Refresh#82]

**Comment by speedyman09** [comment]
Add this to the v3.0 milestone

**Comment by jvyden** [comment]
v3.0 is a major infrastructure overhaul that redesigns many aspects of Refresh. This issue wouldn't really fit with that theme.

I do understand the wish for reviews, though. I'm aware we haven't been focusing on game features for a while now, and I do apologize for that. This issue shouldn't be too hard to implement so we'd accept a community contribution in the meantime.

**Comment by jvyden** [comment]
Everything is abstracted so that you don't have to worry about it while writing API code like this. If you're confused about something then you're free to come ask us in the dev channels on Matrix or Discord, or we can keep this on GitHub if you'd prefer.

You'd basically just need to find the XML schema for reviews and write some code to glue that to the database. That's how most game code works in Refresh, save for some sanitization. Most of the implementation details later will come up in review or later down the line.

**Comment by speedyman09** [comment]
Understood

**Comment by jvyden** [comment]
The best way to write code for a new project is to look at other, similar code.

**Comment by Arcadius2006** [comment]
HOW HAS THIS NOT BEEN ADDED YET??????

**Comment by Arcadius2006** [comment]
it should be noted that LittleBigPlanet does allow you to yay and boo reviews on your own level

i mention this because lighthouse seems to not allow that
